server:
    port: 8090
    address: localhost

spring:
    profiles: dev
    datasource:
        driverClass: org.h2.Driver
        url: jdbc:h2:mem:houston
        serverName: 
        username: 
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true

reverse-proxy:
  host:203.196.144.232
  port:80
  redis-host:203.196.144.232
  redis-port:6379
  redis-password:password

        
# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
  enabled: true
  watchdir:
    - target/classes
