server:
    port: 8090
    address: localhost

spring:
    profiles: dev
    datasource:
        driverClass: org.hsqldb.jdbc.JDBCDriver
        url: jdbc:hsqldb:mem:houston
        serverName: 
        username: 
        password:

    jpa:
        database-platform: org.hibernate.dialect.HSQLDialect
        database: HSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true


        