server:
    port: 8090
    address: 0.0.0.0

spring:
    profiles: dev
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://127.0.0.1:3306/houston
        databaseName: 
        serverName: 
        username: root
        password: password

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: true
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true

reverse-proxy:
  host:203.196.144.232
  port:80
  redis-host:203.196.144.232
  redis-port:6379
  redis-password:password

        
# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
  enabled: true
  watchdir:
    - target/classes
