//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.17 at 02:16:18 PM IST
//


package com.cloudezz.houston.domain;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="form">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="form-element" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="display-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="optional" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="port-config">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="port">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="display-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="default-value" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="volume-config">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="volume-mapping" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="container" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"form", "portConfig", "volumeConfig"})
@XmlRootElement(name = "img-settings")
public class ImgSettings {

  @XmlElement(required = true)
  protected ImgSettings.Form form;
  @XmlElement(name = "port-config", required = true)
  protected ImgSettings.PortConfig portConfig;
  @XmlElement(name = "volume-config", required = true)
  protected ImgSettings.VolumeConfig volumeConfig;

  /**
   * Gets the value of the form property.
   * 
   * @return possible object is {@link ImgSettings.Form }
   * 
   */
  public ImgSettings.Form getForm() {
    return form;
  }

  /**
   * Sets the value of the form property.
   * 
   * @param value allowed object is {@link ImgSettings.Form }
   * 
   */
  public void setForm(ImgSettings.Form value) {
    this.form = value;
  }

  /**
   * Gets the value of the portConfig property.
   * 
   * @return possible object is {@link ImgSettings.PortConfig }
   * 
   */
  public ImgSettings.PortConfig getPortConfig() {
    return portConfig;
  }

  /**
   * Sets the value of the portConfig property.
   * 
   * @param value allowed object is {@link ImgSettings.PortConfig }
   * 
   */
  public void setPortConfig(ImgSettings.PortConfig value) {
    this.portConfig = value;
  }

  /**
   * Gets the value of the volumeConfig property.
   * 
   * @return possible object is {@link ImgSettings.VolumeConfig }
   * 
   */
  public ImgSettings.VolumeConfig getVolumeConfig() {
    return volumeConfig;
  }

  /**
   * Sets the value of the volumeConfig property.
   * 
   * @param value allowed object is {@link ImgSettings.VolumeConfig }
   * 
   */
  public void setVolumeConfig(ImgSettings.VolumeConfig value) {
    this.volumeConfig = value;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="form-element" maxOccurs="unbounded" minOccurs="0">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                 &lt;attribute name="display-name" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                 &lt;attribute name="optional" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"formElement"})
  public static class Form {

    @XmlElement(name = "form-element")
    protected List<ImgSettings.Form.FormElement> formElement;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the formElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the formElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getFormElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ImgSettings.Form.FormElement }
     * 
     * 
     */
    public List<ImgSettings.Form.FormElement> getFormElement() {
      if (formElement == null) {
        formElement = new ArrayList<ImgSettings.Form.FormElement>();
      }
      return this.formElement;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
      return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
      this.name = value;
    }


    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="display-name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="optional" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"value"})
    public static class FormElement {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "type")
      protected String type;
      @XmlAttribute(name = "name")
      protected String name;
      @XmlAttribute(name = "display-name")
      protected String displayName;
      @XmlAttribute(name = "optional")
      protected String optional;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

      /**
       * Gets the value of the name property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getName() {
        return name;
      }

      /**
       * Sets the value of the name property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setName(String value) {
        this.name = value;
      }

      /**
       * Gets the value of the displayName property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getDisplayName() {
        return displayName;
      }

      /**
       * Sets the value of the displayName property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setDisplayName(String value) {
        this.displayName = value;
      }

      /**
       * Gets the value of the optional property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getOptional() {
        return optional;
      }

      /**
       * Sets the value of the optional property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setOptional(String value) {
        this.optional = value;
      }

    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="port" maxOccurs="unbounded" minOccurs="0">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                 &lt;attribute name="display-name" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                 &lt;attribute name="default-value" type="{http://www.w3.org/2001/XMLSchema}short" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"port"})
  public static class PortConfig {

    protected List<ImgSettings.PortConfig.Port> port;

    /**
     * Gets the value of the port property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the port property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ImgSettings.PortConfig.Port }
     * 
     * 
     */
    public List<ImgSettings.PortConfig.Port> getPort() {
      if (port == null) {
        port = new ArrayList<ImgSettings.PortConfig.Port>();
      }
      return this.port;
    }



    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="display-name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="default-value" type="{http://www.w3.org/2001/XMLSchema}short" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"value"})
    public static class Port {

      @XmlAttribute(name = "value")
      protected String value;
      @XmlAttribute(name = "name")
      protected String name;
      @XmlAttribute(name = "display-name")
      protected String displayName;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the name property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getName() {
        return name;
      }

      /**
       * Sets the value of the name property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setName(String value) {
        this.name = value;
      }

      /**
       * Gets the value of the displayName property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getDisplayName() {
        return displayName;
      }

      /**
       * Sets the value of the displayName property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setDisplayName(String value) {
        this.displayName = value;
      }

    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="volume-mapping" maxOccurs="unbounded" minOccurs="0">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                 &lt;attribute name="container" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"volumeMapping"})
  public static class VolumeConfig {

    @XmlElement(name = "volume-mapping")
    protected List<ImgSettings.VolumeConfig.VolumeMapping> volumeMapping;

    /**
     * Gets the value of the volumeMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the volumeMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getVolumeMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImgSettings.VolumeConfig.VolumeMapping }
     * 
     * 
     */
    public List<ImgSettings.VolumeConfig.VolumeMapping> getVolumeMapping() {
      if (volumeMapping == null) {
        volumeMapping = new ArrayList<ImgSettings.VolumeConfig.VolumeMapping>();
      }
      return this.volumeMapping;
    }


    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="container" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"value"})
    public static class VolumeMapping {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "host")
      protected String hostVol;
      @XmlAttribute(name = "container")
      protected String containerVol;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the host property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHostVol() {
        return hostVol;
      }

      /**
       * Sets the value of the host property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setHostVol(String value) {
        this.hostVol = value;
      }

      /**
       * Gets the value of the container property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getContainerVol() {
        return containerVol;
      }

      /**
       * Sets the value of the container property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setContainerVol(String value) {
        this.containerVol = value;
      }

    }

  }

}
